# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 09:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(default='', max_length=10, verbose_name='\u59d3\u540d1')),
                ('gender1', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b1')),
                ('major1', models.CharField(default='', max_length=40, verbose_name='\u4e13\u4e1a1')),
                ('student_id1', models.CharField(default='', max_length=10, verbose_name='\u5b66\u53f71')),
                ('enrollment_year1', models.CharField(default='', max_length=4, verbose_name='\u5165\u5b66\u5e74\u4efd1')),
                ('tel_num1', models.CharField(default='', max_length=11, verbose_name='\u7535\u8bdd1')),
                ('email1', models.EmailField(max_length=30, verbose_name='email1')),
                ('name2', models.CharField(default='', max_length=10, verbose_name='\u59d3\u540d2')),
                ('gender2', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b2')),
                ('major2', models.CharField(default='', max_length=40, verbose_name='\u4e13\u4e1a2')),
                ('student_id2', models.CharField(default='', max_length=10, verbose_name='\u5b66\u53f72')),
                ('enrollment_year2', models.CharField(default='', max_length=4, verbose_name='\u5165\u5b66\u5e74\u4efd2')),
                ('tel_num2', models.CharField(default='', max_length=11, verbose_name='\u7535\u8bdd2')),
                ('email2', models.EmailField(max_length=30, verbose_name='email2')),
                ('name3', models.CharField(default='', max_length=10, verbose_name='\u59d3\u540d3')),
                ('gender3', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b3')),
                ('major3', models.CharField(default='', max_length=40, verbose_name='\u4e13\u4e1a3')),
                ('student_id3', models.CharField(default='', max_length=10, verbose_name='\u5b66\u53f73')),
                ('enrollment_year3', models.CharField(default='', max_length=4, verbose_name='\u5165\u5b66\u5e74\u4efd3')),
                ('tel_num3', models.CharField(default='', max_length=11, verbose_name='\u7535\u8bdd3')),
                ('email3', models.EmailField(max_length=30, verbose_name='email3')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
            options={
                'verbose_name': '\u961f\u4f0d\u4fe1\u606f',
                'verbose_name_plural': '\u961f\u4f0d\u4fe1\u606f',
            },
        ),
    ]
