# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u8d26\u53f7'),
        ),
    ]
