# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='\u8d26\u53f7'),
        ),
    ]
