# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email1',
            field=models.EmailField(blank=True, max_length=30, verbose_name='email1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='email2',
            field=models.EmailField(blank=True, max_length=30, verbose_name='email2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='email3',
            field=models.EmailField(blank=True, max_length=30, verbose_name='email3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='enrollment_year1',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='\u5165\u5b66\u5e74\u4efd1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='enrollment_year2',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='\u5165\u5b66\u5e74\u4efd2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='enrollment_year3',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='\u5165\u5b66\u5e74\u4efd3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='major1',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='\u4e13\u4e1a1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='major2',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='\u4e13\u4e1a2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='major3',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='\u4e13\u4e1a3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name1',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u59d3\u540d1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name2',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u59d3\u540d2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name3',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u59d3\u540d3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_id1',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u5b66\u53f71'),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_id2',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u5b66\u53f72'),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_id3',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u5b66\u53f73'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tel_num1',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='\u7535\u8bdd1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tel_num2',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='\u7535\u8bdd2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tel_num3',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='\u7535\u8bdd3'),
        ),
    ]
