# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171113_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='school1',
            field=models.CharField(default='', max_length=30, verbose_name='\u5b66\u9662'),
        ),
        migrations.AddField(
            model_name='team',
            name='school2',
            field=models.CharField(default='', max_length=30, verbose_name='\u5b66\u9662'),
        ),
        migrations.AddField(
            model_name='team',
            name='school3',
            field=models.CharField(default='', max_length=30, verbose_name='\u5b66\u9662'),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name1',
            field=models.CharField(default='', max_length=5, verbose_name='\u59d3\u540d\u7f29\u5199'),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name2',
            field=models.CharField(default='', max_length=5, verbose_name='\u59d3\u540d\u7f29\u5199'),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name3',
            field=models.CharField(default='', max_length=5, verbose_name='\u59d3\u540d\u7f29\u5199'),
        ),
    ]
