# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171114_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_name1',
            field=models.CharField(default='', max_length=30, verbose_name='\u59d3\u540d\u7f29\u5199'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name2',
            field=models.CharField(default='', max_length=30, verbose_name='\u59d3\u540d\u7f29\u5199'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name3',
            field=models.CharField(default='', max_length=30, verbose_name='\u59d3\u540d\u7f29\u5199'),
        ),
    ]
